=head1 Dist::Metadata

This is sort of a companion to L<Module::Metadata>.
It provides an interface for getting information about a distribution.

This is mostly a wrapper around L<CPAN::Meta>
providing an easy interface to find and load the meta file from a F<tar.gz> file.

If the dist does not contain a meta file
the module will attempt to determine some of that data from the dist.

See module POD for more information.

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Randy Stauner.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
